### ISSUE TITLE
Receiving an error

### ISSUE THREAD

**Issue by wittney** [guilherme-pereira/vcf2sm#4]
When I use vcf2sm pipeline I receive an error about the index being out of range. 
The pipeline inserted in the command line was: python VCF2SM.py -i Results_from_ProductionSNPCaller.vcf -o ouput_02152019.vcf -S SuperMASSA.py -I f1 -d 300 -M 8:10 -f 8 -t 2 -p 0.95

The error response is below: 
Traceback (most recent call last):
  File "VCF2SM.py", line 650, in <module>
    main()
  File "VCF2SM.py", line 646, in main
    process_input_VCF_files(args, parser, SM_input_dir, use_parents, in_file_list, out_file_list)
  File "VCF2SM.py", line 554, in process_input_VCF_files
    process_variant(args, parser, l, f, idx, SM_input_dir, use_parents, par1Idx, par2Idx, jobs)
  File "VCF2SM.py", line 425, in process_variant
    allele_depths = [get_AD_idx_single(vals[i], depth_idx) for i in idx]
IndexError: list index out of rang

**Comment by guilherme-pereira** [comment]
You need to provide either `-g` (pattern of genotype IDs) or `-r` (indices of genotypes) in order to identify individuals to be included in the analysis. E.g., if you have a VCF with 100 samples, use `-r 1:100`.

**Comment by guilherme-pereira** [comment]
This has been fixed by uncommenting `#matplotlib.use('Agg')` in `utilities.py` from SuperMASSA source code.
