### ISSUE TITLE
"No such file or directory" a missing file  error

### ISSUE THREAD

**Issue by dosshra** [guilherme-pereira/vcf2sm#5]
I am trying to run VCF2SM python script to call genotypes from tetraploid GBS data. The vcf file was generated by bcftools. I am running the command:
python2.7 VCF2SM.py -i H.bulbosum.vcf -o H.bulbosum_SM_call.vcf -S ./SM/src/SuperMASSA.py -I ploidy  -a DPR   -M 4:6 -f 4 -p 0.80 -n 0.90 -c 0.75 -t 4

The script runs to a certain point where it stops with the message "No such file or directory: '/storage/hanan/vcf2sm/InputFiles/H.bulbosum.vcf_contig_22579_4408.txt'"
The script generates files for each SNP in the InputFiles directory, but some SNP files are missing.

**Comment by guilherme-pereira** [comment]
This happens when you have variants in identical positions, but it has been fixed now.
