### ISSUE TITLE
Please note that VCF2SM is not compatible with Python 3.

### ISSUE THREAD

**Issue by jtahir** [guilherme-pereira/vcf2sm#7]
Hi Guilherme
I am trying to use this pipeline but realizing that Please note that VCF2SM is not compatible with Python 3. I work in Plant and Food Research, NZ and we have a backend server where we run our pipelines. Unfortunately, since the Jan, 2020 we are not using Python 2. Is there a possibility to have a version of this pipeline that is compatible with Python 3,
Please if you can share you email address, I have more questions regarding my datatset (diploid and tetraploid kiwifruit Captureseq/GBS) and interested in dosage calling in polyploids.
cheers
Jibran
Scientist
Molecular and Digital Breeding
The New Zealand Institute for Plant & Food Research Limited

**Comment by guilherme-pereira** [comment]
Hi Jibran,

We are aware of Pyhton 2 and 3 incompatibilities. Most servers can provide a way of using either versions. In your case, they could provide a specific environment for VCF2SM (maybe using conda or a container). Feel free to email me at guispb@gmail.com.

Thanks,

Guilherme.
